"""PRC/MLR-approved ONAPGO discussion guides (SPN.830.2025-0010/-0011/-0012), transcribed verbatim.
Item = (stage, seq, kind, text, qtype, options, show_qid, show_vals, dq_vals, sched)
kind: say=advocate reads aloud · instr=advocate/dev instruction · q=form field
sched: 'hcp' = answer sets the member's HCP appointment date (drives pre/post call scheduling)
"""
ISI_SERIOUS="The serious side effects include: allergic reaction, blood clots, nausea and vomiting, sleepiness or falling asleep during the day, dizziness, falls, infusion site reaction, hallucinations or psychotic-like behavior, sudden uncontrolled movements (dyskinesia), low red blood cells (hemolytic anemia), strong (intense) urges, heart problems, serious heart rhythm changes (QT prolongation), tissue changes (fibrotic complications), and prolonged painful erections (priapism)."
ISI_COMMON="Common side effects of ONAPGO include: headache and trouble falling asleep or staying asleep (insomnia). If you were to experience any of this with ONAPGO or any other medication this is something that you should talk to your doctor about."
CONTRA=[  # (question, taking-option, not-option)
 ("Are you taking certain medicines to treat nausea including ondansetron, granisetron, dolasetron, palonosetron, and alosetron?","I am taking one of the above.","I am NOT taking one of the above"),
 ("Are you allergic to apomorphine hydrochloride?","Yes, I am allergic to apomorphine hydrochloride.","I am NOT allergic"),
 ("Are you allergic to a sulfite called sodium metabisulfite which is in ONAPGO?","I am allergic to the above.","I am NOT allergic to the above."),
 ("Are you allergic to hydrochloric acid which is in ONAPGO?","I am allergic to the above.","I am NOT allergic to the above."),
]
def contra_items(stage,seq0,show_qid,show_vals):
    out=[]; s=seq0
    for i,(q,bad,good) in enumerate(CONTRA):
        out.append((stage,s,'q',q,'radio',f'{bad}|{good}',show_qid,show_vals,bad,'')); 
        out.append((stage,s+1,'instr','If taking/allergic: end form — member does not qualify (auto-flagged DQ). Otherwise continue.','','',str(s),bad,'',''))
        s+=2
    return out,s

I=[]  # ---------------- INITIAL ----------------
S='initial'
I+=[(S,1,'say',"[Identify Ourselves & Sponsor] Our goal is to provide you with fair and balanced information that can be useful in discussing your Parkinson's symptoms with your doctor to discuss what options may be right for you. We are not your physician, and we cannot prescribe anything, we just want to make you aware of your options.",'','','','','',''),
 (S,2,'say',"<Member Name> the following information is sponsored by Supernus, the makers of ONAPGO (apomorphine hydrochloride), which is used to treat motor fluctuations (OFF episodes) in adults with advanced Parkinson's disease. May I speak to you on their behalf to give a bit more information about this Parkinson's treatment option because you indicated you were experiencing OFF time? I want to assure you that none of your personal identifying information will be made accessible to Supernus.",'','','','','',''),
 (S,3,'q','Consent to proceed on behalf of sponsor?','radio','Yes|No','','','',''),
 (S,4,'say','Okay, I understand. Unfortunately, this is all the information I have for you today. I would love to check in and see how your appointment went in a few weeks. Thank you for your time! — OR — Okay, I understand. We respect your decision. You always have the option to reach out to me if you\'d like to receive additional information.','','','3','No','',''),
 (S,5,'instr','If no: offer PPI and play ISI, then end call.','','','3','No','',''),
 (S,6,'say',"[Qualify Patient / Determine Appointment] From our last conversation [your online submission] it looks like you were experiencing daily OFF time that can be disruptive. Is that correct?",'','','3','Yes','',''),
 (S,7,'q','Daily disruptive OFF time confirmed?','radio','Yes|No','3','Yes','',''),
 (S,8,'say',"I'm sorry to hear that. Levodopa is a mainstay Parkinson's therapy but over time with Parkinson's it becomes less reliable, there is a shorter duration of symptom benefit from each dose, and GOOD ON fades.",'','','3','Yes','',''),
 (S,9,'q','You also indicated that your OFF time can look/feel like: (select all the member reports)','check','Difficulty starting movements|Feeling stuck or slow|Shuffling|Low voice while talking|Tremor|Balance problems|Stiffness and difficulty getting out of a chair','3','Yes','',''),
 (S,10,'q','Are you still experiencing OFF time in your day-to-day life? Would you like to share more of your OFF-time experiences with me? As your patient advocate, I am here for you.','radio','Yes|No','3','Yes','',''),
 (S,11,'say',"I'm sorry to hear that... I encourage you to bring this to the attention of and discuss with <Neurologist Name>.",'','','10','Yes','',''),
 (S,12,'q','When is the next appointment with the neurologist / HCP? [Determine Appointment — drives the Pre-HCP call]','date','','3','Yes','','hcp'),
 (S,13,'q','Are you still taking oral levodopa and any other medications for PD?','radio','Yes|No','3','Yes','',''),
 (S,14,'say','One of the challenges with treating OFF time is getting your full levodopa dose to the brain to help control and coordinate movements. Did you know only a small amount of the levodopa taken orally makes it to the brain? If you are interested I could explain a little bit about why this is the case.','','','13','Yes','',''),
 (S,15,'q','Interested in the explanation? (pause to gauge interest)','radio','Yes|No','13','Yes','',''),
 (S,16,'say','GI issues or your diet (ie, protein) can interfere with the absorption of oral levodopa. Your doctor may have told you to stagger your medication doses and mealtimes, take medication on an empty stomach and limit your protein intake. Absorption issues with levodopa can delay it entering the bloodstream. Also, the brain has a barrier, making it hard for levodopa to travel from your stomach to your brain.','','','15','Yes','',''),
 (S,17,'q','Would you like to learn about a treatment option for OFF time that you could discuss with your doctor? And if so, is now a good time?','radio','Yes|No — not a good time (reschedule)|No — end call','3','Yes','',''),
 (S,18,'say',"Perfect. I'd like to talk to you about a treatment option that was FDA approved in February 2025 called ONAPGO. As I mentioned earlier, ONAPGO is a prescription medication used to treat motor fluctuations (OFF episodes) in adults with advanced Parkinson's disease. ONAPGO works with your oral levodopa to help provide less daily OFF time and more continuous GOOD ON time. Unlike levodopa, it has a more direct journey to the brain without the same obstacles. ONAPGO is not impacted by protein in your diet. This means you do not need to plan around meal times.",'','','17','Yes','',''),
 (S,19,'q','Do you want to learn more?','radio','Yes|No','17','Yes','',''),
 (S,20,'say','ONAPGO is a wearable infusion device that is applied just under the skin (subcutaneous) — similar to insulin devices for people with diabetes — and provides continuous delivery of apomorphine during the waking day.','','','19','Yes','',''),
 (S,21,'say','Of course all PD medications have side effects and important safety information you should know, and ONAPGO should not be taken if any of the following are true:','','','17','Yes','','')]
ci,seq=contra_items(S,22,'17','Yes'); I+=ci   # 22..29
I+=[(S,seq,'say','Thank you for letting me check on those important contraindications. (Pause, acknowledge member response.)','','','17','Yes','',''),
 (S,seq+1,'q','GOOD ON time is when you are experiencing good symptom control and are not bothered by OFF time or dyskinesia. Would you like to share with me what GOOD ON time might look like for you? (record response)','text','','17','Yes','',''),
 (S,seq+2,'q','How much GOOD ON time do you usually have in your day? How long does it last? Is it always the same amount of time? (record response)','text','','17','Yes','',''),
 (S,seq+3,'say',"ONAPGO is a device aided therapy, approved by the FDA February 2025, that can help you achieve more continuous GOOD ON time each day and help make your days with Parkinson's more predictable with less OFF time.",'','','17','Yes','',''),
 (S,seq+4,'q','Would you like to know how ONAPGO is worn?','radio','Yes|No','17','Yes','',''),
 (S,seq+5,'say','ONAPGO is administered just under the skin (subcutaneous infusion) with the ONAPGO device. It does not require surgery, and it uses one cartridge a day, no refrigeration is needed. Before first use, you and your care partner will receive education about the ONAPGO device, including detailed instructions.','','',str(seq+4),'Yes','',''),
 (S,seq+6,'q','Would you like to know the size of the ONAPGO device?','radio','Yes|No','17','Yes','',''),
 (S,seq+7,'say','ONAPGO is about the size and weight of an iPhone 15. It is 6x2 inches and 0.4 lbs. It is similar to insulin devices prescribed to people with diabetes.','','',str(seq+6),'Yes','',''),
 (S,seq+8,'say','[ISI] Let\'s go over some Important Safety Information for ONAPGO: '+ISI_SERIOUS+' '+ISI_COMMON,'','','3','Yes','',''),
 (S,seq+9,'say',"[Discussing OFF time with Doctor Tips] It's important to share with your doctor what you experience every day, good and bad, like what we have discussed today, so they can help provide you with the best treatment plan. Should I send you information about what we discussed today? We encourage you to review it and bring it to your next appointment to help you share your symptoms and ask your doctor if ONAPGO may be right for you.",'','','3','Yes','',''),
 (S,seq+10,'q','Would you like the ONAPGO Patient Information sent to you?','radio','Yes|No','3','Yes','',''),
 (S,seq+11,'q','Preference on how it is sent (confirm address)','radio','Email (confirm email address)|Mail (confirm mailing address)|Declined',str(seq+10),'Yes','',''),
 (S,seq+12,'q','ONAPGO has the Circle of Care™ Program, which provides ongoing comprehensive support and education, including education and support from a Clinical Nurse Navigator. Would you like to hear more?','radio','Yes|No','3','Yes','',''),
 (S,seq+13,'say','With the Circle of Care program, after your doctor prescribes ONAPGO, HUB coordinators will help with navigating insurance coverage, benefits, and available assistance programs. They will work with the patient and doctor\'s office as needed and coordinate with the specialty pharmacy for medication delivery. Additionally, Clinical Nurse Navigators will work with the patient and doctor to help them get started on ONAPGO. They are registered nurses who provide training and education on wearing and using the ONAPGO device.','','',str(seq+12),'Yes','',''),
 (S,seq+14,'say','Okay. This is all the information I have for you today. You can always visit ONAPGO.com to learn more about ONAPGO and the Circle of Care Program.','','',str(seq+12),'No','',''),
 (S,seq+15,'say',"[Full ISI Prompt] It's been great chatting with you today. I'd like for you to stay on the line to hear additional Important Safety Information for ONAPGO. And as we talked about, I will be sending you the information after this call. Please stay on to listen and you can also learn more about ONAPGO by visiting ONAPGO.com. Do you have any questions before we close this call?",'','','3','Yes','',''),
 (S,seq+16,'q','Member questions before closing (record; for any treatment question answer: "That is a great question. I am not a physician so I can\'t say, please speak with your doctor about this.")','text','','3','Yes','',''),
 (S,seq+17,'instr','<Member Name>, it was an absolute pleasure speaking with you today. Close call with prerecorded ISI.','','','3','Yes','','')]

P=[]  # ---------------- PRE-HCP ----------------
S='pre_hcp'
P+=[(S,1,'say','[Name], last time we spoke, you informed us of an upcoming appointment with your doctor on [date of upcoming appointment]. Is this still correct and scheduled?','','','','','',''),
 (S,2,'q','Appointment still correct and scheduled?','radio','Yes|No','','','',''),
 (S,3,'q','We have a different date in our record. Did we get the date wrong, was it rescheduled, or cancelled?','radio','Wrong Date|Rescheduled|Cancelled','2','No','',''),
 (S,4,'q','I apologize for the confusion. When is your next scheduled appointment?','date','','3','Wrong Date|Rescheduled','','hcp'),
 (S,5,'say','We care about you [Name] and certainly do not want you to have to deal with these daily OFF time disruptions when treatment options are available. We hope you are able to schedule an appointment with your health care provider soon to discuss the OFF time that you are still experiencing. Would you like us to connect you with resources in your area? I will follow up with you in the future to get an update. [Resources: patient support groups and names of neurologists/movement disorder specialists in their area]','','','3','Cancelled','',''),
 (S,6,'q','Great. After our initial conversation, we provided you with some information, through both email and mail so you could share this information with your physician at your upcoming appointment. Did you receive the email and mailed information?','radio','Yes|No','','','',''),
 (S,7,'say','I am sorry to hear you did not receive the information. I will be sure to get you this right away, which will include the ONAPGO (apomorphine hydrochloride) Important Safety Information, Patient Information, and Patient Instructions for Use.','','','6','No','',''),
 (S,8,'instr','If no email: initiate email. If no mailer: assure them you will resend and verify email/mailing address.','','','6','No','',''),
 (S,9,'q','My goal is to make sure you feel ready to speak with your doctor about your OFF Time at your appointment. Your doctor might have a hard time treating symptoms that he/she does not know you are experiencing. Can we chat about a few ways to communicate your PD symptoms with your doctor that you might not have considered yet?','radio','Yes|No','','','',''),
 (S,10,'say','Great, the first thing I recommend is a strong start to the conversation with your doctor/nurse. What do people typically say when someone asks "how are you today?" I normally say good or fine, even when I am not. How about you? (Pause.) A lot of people tell their doctor they are good or fine when they are bad or even horrible because pleasantries are important. But when your doctor/nurse walks in and asks how you are, consider that this isn\'t a social question or a routine encounter. Consider this the initial diagnostic question and part of your patient assessment. My suggestion is if you are not doing well, and this is important, say something like: I\'m NOT well, or my OFF time is very troublesome, or whatever it is that is bothering you and that you want addressed.','','','9','Yes','',''),
 (S,11,'q','What might you say when the doctor asks, how are you? (record response)','text','','9','Yes','',''),
 (S,12,'say','Another suggestion is to communicate what it is you are not doing these days that you would do if you had more GOOD ON time. Your story is important and you should be understood. Is there something you want to do more but can\'t because of OFF time symptoms? (Pause.) Ok, so tell your doctor that. Express how OFF time is limiting you in these specific ways.','','','9','Yes','',''),
 (S,13,'q','Here\'s another important consideration. If it is ok that I ask, is OFF time affecting your relationships with friends or family?','radio','Yes|No','9','Yes','',''),
 (S,14,'instr','If Yes: "May I please suggest that you tell your doctor this?" · If No: "I am really glad to hear that."','','','13','Yes|No','',''),
 (S,15,'q','May I please speak to you again about a therapy approved in 2025 on behalf of one of our sponsors, Supernus, the manufacturer of ONAPGO (apomorphine hydrochloride), which is used to treat motor fluctuations (OFF episodes) in adults with advanced Parkinson\'s disease?','radio','Yes|No','','','',''),
 (S,16,'say','Okay, I understand. This is all the information I have for you today. I would love to check in and see how your appointment went in a few weeks. Thank you for your time! — OR — Okay, I understand. We respect your decision. You always have the option to reach out to me if you\'d like to receive additional information. (Offer PPI and play ISI.)','','','15','No','',''),
 (S,17,'say','Last time we spoke, we talked about ONAPGO (apomorphine hydrochloride). Do you recall that this is not an oral medication but rather a wearable infusion device that is applied just under the skin (subcutaneous) — similar to insulin devices for people with diabetes — and provides continuous treatment during the waking day for more consistent control of OFF time? (Pause.) Can I double check a few contraindications, which are reasons that you would not be a good candidate for this medication?','','','15','Yes','','')]
ci,seq=contra_items(S,18,'15','Yes'); P+=ci  # 18..25
P+=[(S,seq,'q','I would like to see your OFF time reduced, your ON time increased and an improvement in your Parkinson\'s symptoms. Since you have told me you have troublesome OFF despite the use of multiple oral medications and you do not think you have these contraindications, I suggest we review some of the benefits and risks of ONAPGO together so you can discuss them further with your doctor. Is that ok?','radio','Yes|No','15','Yes','',''),
 (S,seq+1,'say','ONAPGO can provide continuous treatment during the waking day for more consistent control of OFF time with more GOOD ON time but there are risks. I will first cover serious side effects and then common side effects. '+ISI_SERIOUS+' '+ISI_COMMON,'','',str(seq),'Yes','',''),
 (S,seq+2,'q','Thanks for listening to that detailed explanation of the potential risks and benefits. I can repeat any of this information if that would be helpful?','radio','Yes — re-read requested sections|No','15','Yes','',''),
 (S,seq+3,'say','I hope you feel more prepared for your upcoming visit. We discussed ways to communicate OFF time with your doctor and a specific treatment option called ONAPGO. If it is ok with you, I will reach out after your appointment to see how your visit went. Do you have any questions before we close this call?','','','','','',''),
 (S,seq+4,'q','Member questions before closing (record; treatment questions: "That is a great question. I am not a healthcare provider so I can\'t say, please speak with your doctor about this.")','text','','','','',''),
 (S,seq+5,'q','Would you like the ONAPGO Patient Information sent to you?','radio','Yes|No','','','',''),
 (S,seq+6,'q','Preference on how it is sent (confirm address)','radio','Email (confirm email address)|Mail (confirm mailing address)|Declined',str(seq+5),'Yes','',''),
 (S,seq+7,'instr','[Member Name], it was an absolute pleasure speaking with you today. I hope you have a productive visit with your doctor. Close call with prerecorded ISI.','','','','','','')]

O=[]  # ---------------- POST-HCP ----------------
S='post_hcp'
O+=[(S,1,'say','[Identify Ourselves & Sponsor] Our goal is to provide you with information that can be useful in discussing your Parkinson\'s symptoms with your healthcare provider to discuss what options may be right for you. We are not your physician, and we cannot prescribe anything, we just want to make you aware of a treatment option. <Member Name> the following information is sponsored by Supernus, the makers of ONAPGO (apomorphine hydrochloride), which is used to treat motor fluctuations (OFF episodes) in adults with advanced Parkinson\'s disease. I want to assure you that none of your personal identifying information will be made accessible to Supernus.','','','','','',''),
 (S,2,'q','To begin, are you still experiencing OFF time and is it bothering you?','radio',"I'm still experiencing OFF Time and it disrupts my day and bothers me|I'm still experiencing OFF Time and it is NOT bothersome to me|I am no longer experiencing OFF Time",'','','',''),
 (S,3,'q','Did your doctor make any changes to your Parkinson\'s treatment/medication plan? (check all that apply)','check','My doctor prescribed another Parkinson\'s treatment for me (not ONAPGO)|My doctor said my OFF symptoms are not bad enough and made no change in treatment|My doctor made no changes and said we would check at the next appointment|My doctor changed the dose/timing of my current medications (other than C/L)|My doctor changed the dose/timing of my C/L|My doctor suggested DBS|My doctor suggested another continuous subcutaneous infusion|My doctor suggested Physical/Occupational Therapy or other exercise program|My doctor prescribed ONAPGO, but my insurance will not cover it|My doctor prescribed ONAPGO, but the copay was too expensive|My doctor prescribed ONAPGO and I am waiting to receive my medication and start treatment|My doctor prescribed ONAPGO and I have started treatment','','','',''),
 (S,4,'say','Thanks for telling me about that. You don\'t have to accept the daily disruptions from OFF time, there are treatments that can help. We encourage you to go back and see your doctor with our updated HCP discussion guide. Sometimes it\'s helpful to take a video of your OFF time and share it with your doctor. What do you think? (Pause.) If your neurologist is not a movement disorder specialist or you feel like you would like to add another member to your healthcare team, you can find MDS names in your local area by visiting https://mds.movementdisorders.org/directory/. Would you like to write that down?','','','2',"I'm still experiencing OFF Time and it disrupts my day and bothers me",'',''),
 (S,5,'q','It is common for doctors to receive feedback from patients in between appointments and they may be able to help you over the phone or possibly bring you in for an earlier appointment. Would you like to call your doctor to make another appointment to talk about your OFF time and what treatment option could be right for you?','radio','Yes|No','2',"I'm still experiencing OFF Time and it disrupts my day and bothers me",'',''),
 (S,6,'instr','IF YES: I am glad to hear it. I\'ll give you a call next week to see when your new appointment is. (System schedules a follow-up in 1 week; a new Pre-HCP call will be scheduled once the date is known.) · IF NO: That\'s okay — capture the next appointment below. (Offer PPI and play ISI.)','','','5','Yes|No','',''),
 (S,7,'q','When is your next appointment scheduled? (drives the next Pre-HCP call)','date','','','','','hcp'),
 (S,8,'say','[ISI] '+ISI_SERIOUS+' '+ISI_COMMON,'','','','','',''),
 (S,9,'q','Did you have the chance to discuss ONAPGO with your doctor at this recent appointment?','radio','Yes|No','','','',''),
 (S,10,'q','Why do you think you were not able to discuss ONAPGO with your doctor? (check all that apply)','check','I didn\'t express my OFF time to my doctor|My doctor did not bring ONAPGO up as an option|My doctor did not have much time for me / listen to me / was running behind|I am concerned about the cost|I am worried about side effects|I am worried about wearing a device|I\'m not interested in ONAPGO|I discussed a different treatment option with my doctor|I had other concerns I discussed instead','9','No','',''),
 (S,11,'q','Would you please share more details as to why you may not be interested in ONAPGO if you are still experiencing OFF time? (Free response — listen and note the patient\'s concerns in detail. Acknowledge member.)','text','','9','Yes','',''),
 (S,12,'q','Do you have any questions? (record; treatment questions: "That is a great question. I am not a healthcare provider so I can\'t say, please speak with your doctor about this.")','text','','','','',''),
 (S,13,'q','Would you like the ONAPGO Patient Information sent to you?','radio','Yes|No','','','',''),
 (S,14,'q','Preference on how it is sent (confirm address)','radio','Email (confirm email address)|Mail (confirm mailing address)|Declined','13','Yes','',''),
 (S,15,'instr','[Member Name], it was an absolute pleasure speaking with you today. I hope we can stay in touch. Please stay on the line to listen to the Important Safety Information. Close call with prerecorded ISI.','','','','','','')]

GUIDE_ITEMS = I+P+O
SCRIPTS={
 'initial':('ONAPGO Initial Telephone Discussion Guide (SPN.830.2025-0010)','PRC/MLR-approved Initiation Education guide. Read the scripted lines verbatim; record answers as you go. Contraindication answers auto-flag DQ.'),
 'pre_hcp':('ONAPGO Branded Pre-HCP Appointment Discussion Guide (SPN.830.2025-0011)','PRC/MLR-approved. Served up to 3x in the 10 days before the HCP appointment.'),
 'post_hcp':('ONAPGO Post-HCP Telephone Discussion Guide (SPN.830.2025-0012)','PRC/MLR-approved. Served up to 3x starting 4 weeks after the appointment.'),
}
